# spring配置
spring:
  # 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 连接本地数据库
    url:
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password:
    # hikari数据库连接池配置
    hikari:
      idleTimeout: 30000
      maximumPoolSize: 10
  # jackson时间格式化
  jackson:
    # 设置时区
    time-zone: GMT+8
    # 当序列化对象中包含日期类型的参数时，配置其转换的格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 序列化的参数，默认值为always指所有
    default-property-inclusion: always
  # redis配置
  redis:
    database: 0
    host:
    port:
    password:
    # 连接超时时长（毫秒）
    timeout: 6000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 16
        # 连接池最大阻塞等待时间,单位毫秒（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5